[package]
name = "rustls"
version = "0.1.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls is a modern TLS library written in Rust."
homepage = "https://github.com/ctz/rustls"
repository = "https://github.com/ctz/rustls"

[dependencies]
untrusted = "0.3.1"
time = "0.1.35"
base64 = "~0.2.0"
log = "0.3.6"

[replace]
"ring:0.2.0" = { git = "https://github.com/briansmith/ring", rev = "ec39fbd" }

[dependencies.ring]
git = "https://github.com/briansmith/ring"
features = [ "rsa_signing" ]
rev = "ec39fbd"

[dependencies.webpki]
git = "https://github.com/ctz/webpki"
rev = "9c855fd"

[dev-dependencies]
env_logger = "0.3.3"
mio = "0.5.1"
docopt = "0.6"
rustc-serialize = "0.3"
