[package]
name = "rustls"
version = "0.1.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls is a modern TLS library written in Rust."
homepage = "https://github.com/ctz/rustls"
repository = "https://github.com/ctz/rustls"

[dependencies]
untrusted = "0.3.1"
time = "0.1.35"
base64 = "~0.2.0"
log = "0.3.6"
ring = { version = "0.3", features = ["rsa_signing"] }
webpki = "0.2.1"

[dev-dependencies]
env_logger = "0.3.3"
mio = "0.5.1"
docopt = "0.6"
rustc-serialize = "0.3"
