[package]
name = "rustls"
version = "0.1.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls is a modern TLS library written in Rust."
homepage = "https://github.com/ctz/rustls"
repository = "https://github.com/ctz/rustls"

[dependencies]
untrusted = "0.2.0"
ring = { version = "0.1.0", git = "https://github.com/ctz/ring", features = ["rsa_signing"] }

# pointed at my fork for the moment
webpki = { version = "0.1.0", git = "https://github.com/ctz/webpki" }

time = "0.1.35"
rustc-serialize = "0.3"
log = "0.3.6"

[dev-dependencies]
env_logger = "0.3.3"
mio = "0.5.1"
docopt = "0.6"
