[package]
name = "rustls"
version = "0.6.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls is a modern TLS library written in Rust."
homepage = "https://github.com/ctz/rustls"
repository = "https://github.com/ctz/rustls"
categories = ["network-programming", "cryptography"]

[dependencies]
untrusted = "0.5"
time = "0.1.37"
base64 = "0.5"
log = { version = "0.3.6", optional = true }
ring = { version = "0.8", features = ["rsa_signing"] }
webpki = "0.11"

[features]
default = ["logging"]
logging = ["log"]

[dev-dependencies]
log = "0.3.7"
env_logger = "0.4.2"
mio = "0.5"
docopt = "0.7"
rustc-serialize = "0.3"
webpki-roots = "0.9"
regex = "0.2"

[[example]]
name = "bogo_shim"
path = "examples/internal/bogo_shim.rs"

[[example]]
name = "trytls_shim"
path = "examples/internal/trytls_shim.rs"

[[example]]
name = "bench"
path = "examples/internal/bench.rs"

[[example]]
name = "tlsclient"
path = "examples/tlsclient.rs"

[[example]]
name = "tlsserver"
path = "examples/tlsserver.rs"
