[package]
name = "rustls"
version = "0.1.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]

[dependencies]
ring = { version = "0.1.0", git = "https://github.com/briansmith/ring" }
webpki = { version = "0.1.0", git = "https://github.com/briansmith/webpki" }

mio = "0.5.1"
time = "0.1.35"
