[package]
name = "rustls"
version = "0.10.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls is a modern TLS library written in Rust."
homepage = "https://github.com/ctz/rustls"
repository = "https://github.com/ctz/rustls"
categories = ["network-programming", "cryptography"]

[dependencies]
untrusted = "0.5"
time = "0.1.37"
base64 = "0.6"
log = { version = "0.3.6", optional = true }
ring = { version = "0.11", features = ["rsa_signing"] }
webpki = "0.16"
sct = "0.1.2"

[features]
default = ["logging"]
logging = ["log"]
dangerous_configuration = []

[dev-dependencies]
log = "0.3.7"
env_logger = "0.4.2"
mio = "0.6"
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
webpki-roots = "0.13"
ct-logs = "0.1"
regex = "0.2"

[[example]]
name = "bogo_shim"
path = "examples/internal/bogo_shim.rs"
required-features = ["dangerous_configuration"]

[[example]]
name = "trytls_shim"
path = "examples/internal/trytls_shim.rs"

[[example]]
name = "bench"
path = "examples/internal/bench.rs"

[[example]]
name = "tlsclient"
path = "examples/tlsclient.rs"

[[example]]
name = "tlsserver"
path = "examples/tlsserver.rs"

[[example]]
name = "simpleclient"
path = "examples/simpleclient.rs"
