[package]
name = "rustls"
version = "0.1.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]

[dependencies]
ring = { version = "0.1.0", git = "https://github.com/briansmith/ring" }

# pointed at my fork for the moment
webpki = { version = "0.1.0", git = "https://github.com/ctz/webpki" }

time = "0.1.35"
rustc-serialize = "0.3"
log = "0.3.6"

[dev-dependencies]
mio = "0.5.1"
docopt = "0.6"
